### ISSUE TITLE
Authors should be required to articulate a summary of changes

### ISSUE THREAD

**Issue by amyjko** [acm-toce/documentation#13]
Offer guidance on what a good summary of changes looks like, perhaps even a template for authors to follow to streamline editorial review.

**Comment by amyjko** [comment]
Drafted here:

https://dl.acm.org/journal/toce/author-guidelines?pbEditor=true#submitting-revisions

Asked board for feedback.

**Comment by honda00** [comment]
Brett is working on this currently. https://docs.google.com/document/d/1YK9Y0q3jiWQJ5AijKi2pUSAhk4BaNObyrRxKGCaMWe0/edit

**Comment by amyjko** [comment]
Revision posted: https://dl.acm.org/journal/toce/author-guidelines?pbEditor=true#submitting-revisions
