### ISSUE TITLE
Journal paper distinctions

### ISSUE THREAD

**Issue by amyjko** [acm-toce/documentation#2]
Paper awards in archival conferences have become an important resource for helping signal the rigor and merit of authors and their work. TOCE lacks any such distinctions, which is a missed opportunity to celebrate our community, communicate its rigor, and make its editorial standards explicit. Create an awards process and begin recognizing work.

**Comment by honda00** [comment]
Delete / merge with [Paper recognitions#67] (https://github.com/acm-toce/documentation/issues/67)

**Comment by amyjko** [comment]
Closing, #67 has the details.
