### ISSUE TITLE
Cover letter guidelines

### ISSUE THREAD

**Issue by amyjko** [acm-toce/documentation#4]
Many authors report not knowing what to include in a cover letter or whether one is required, creating confusion and squandering a critical opportunity to gather context from authors to help with editorial decisions. Create a document that gives authors this guidance, setting clear expectations and offering pointers on the types of content a cover letter might include.

**Comment by amyjko** [comment]
Drafted here: 

https://dl.acm.org/journal/toce/author-guidelines?pbEditor=true#submitting-revisions

Asked board for feedback.

**Comment by honda00** [comment]
Brett is working on this.

**Comment by amyjko** [comment]
There are basically two kinds of submissions: new ones and revised ones. We just did some work on the second category, where cover letters are mostly summaries of revisions, so I think this issue primarily concerns new submissions. Fortunately, you can create and not submit a new submission, and later delete it, so you should be able to see everything we ask there.

Here's the gist:

* Manuscript type
* Title
* Abstract
* File upload
* Computing classification
* Authors and institutions
* Suggested reviewers
* Funders
* ACM Plagiarism pledge

... and then a vague "Cover letter" field, which is either a text box with 32768 character limit, or a file upload, with no other instructions.

Here's a screenshot of the cover letter field:

![Image](https://github.com/acm-toce/documentation/assets/552276/1f09b587-23f3-4ac7-b236-09016ca48507)

Some of the key things for a new submission I can think of that aren't covered by the other metadata:

* Are there any other related submissions that the AE or reviewers should be aware of that aren't directly addressed in the manuscript draft itself?
* What kinds of reviewer expertise is necessary to adequately review the paper?
* Are there any people that should not review, or other conflicts the AE should be aware of?

These are all things that could be added to the submission form, but it turns out that all edits to that form have to go through S1, not even the Journals staff can do it, so the cover letter is our catch all for other content. We should be able to add a link to guidance on the cover letter in the author guide, however.

**Comment by honda00** [comment]
I decided to start with a content outline. Comments and suggested additions, etc. welcome! https://docs.google.com/document/d/10_86w6wQCHLdsklRFoRVpJr-hP-E-_KVK_YEQD93v1g/edit

**Comment by amyjko** [comment]
Thanks! Looks like I don't have permission. Can you move it into the journal's shared drive? I made a folder for this issue:

https://drive.google.com/drive/u/0/folders/1d-iPTL5-HrO5FoZ7B73tNV6DEpclvIl8

**Comment by honda00** [comment]
Doh! I thought I was on the TOCE drive! I've put what I've got so far in that folder now.

**Comment by amyjko** [comment]
Thanks! Commented.

**Comment by honda00** [comment]
Resolved some, commented on others.

**Comment by honda00** [comment]
Over to you @amyjko. Short intro verbiage added, comments cleared/implemented. Some outstanding comments in the GDoc, some new.

**Comment by amyjko** [comment]
Adding link to the Google Doc here, since the others above are incorrect:

https://docs.google.com/document/d/1w_B0a-7Jbc-zpeSe4PETi6DA8eeGRoYbekTVIe1Lju0/edit

**Comment by amyjko** [comment]
Okay, commented on [the doc](https://docs.google.com/document/d/1w_B0a-7Jbc-zpeSe4PETi6DA8eeGRoYbekTVIe1Lju0/edit). I think it's ready to post; what do you think? Anything else you want to change?

**Comment by honda00** [comment]
Looks good to me!

**Comment by amyjko** [comment]
Great, it's online, closing.
