### ISSUE TITLE
Clarify second AE check in Unsubmit guidelines

### ISSUE THREAD

**Issue by kfisler** [acm-toce/documentation#63]
We agreed in Discord that a second AE should look at a paper prior to unsubmitting. This agreement should be added to the Associate Editor guidelines document in the "unsubmit" area (including the instructions of how to pass this to a second AE).

I was also a bit surprised that the "unsubmit" option resulted in my emailing the authors directly, rather than having the message go to the EIC for a check (as with decisions). If this is the expected behavior, worth making that explicit in the Unsubmit instructions as well.

**Comment by amyjko** [comment]
Thanks Kathi! I'll work on cleaning this up.

**Comment by amyjko** [comment]
This should be clarified now: https://github.com/acm-toce/documentation/wiki/Associate-Editor-Guidelines#step-2-decide-whether-to-review
