### ISSUE TITLE
Revise "About TOCE" journal scope

### ISSUE THREAD

**Issue by amyjko** [acm-toce/documentation#9]
This page needs a refresh to reflect the journal's broadened scope

https://dl.acm.org/journal/toce/scope

In particular, it needs to have room for design contributions and design analyses that don't necessarily have empirical contributions.

**Comment by amyjko** [comment]
Need to consult with Laura Lander on this, as it may need to be approved by the Publications Board.

**Comment by tclear** [comment]
It may also be worth considering how the journal is addressing [or should be addressing?] new curricula and subfields of Computing and CS+x e.g. cybersecurity and data science cf. https://www.acm.org/education/curricula-recommendations

**Comment by amyjko** [comment]
Drafted here: https://github.com/acm-toce/documentation/blob/main/Website/about.md

**Comment by amyjko** [comment]
Gave two weeks for the committee to review. I've now routed it to the Journals Manager for approval by the ACM Publications Board.

**Comment by amyjko** [comment]
ACM Publications Board is reviewing now.

**Comment by amyjko** [comment]
No updates from the review board. I asked Laura for an update.

**Comment by amyjko** [comment]
Will be discussed: "The revised scope will be discussed during the in-person editorial board meeting 6/23-24."

**Comment by amyjko** [comment]
It was approved this week. Starrat will get it online at some point.

**Comment by amyjko** [comment]
Done! Scope is live.
